version: '3.2'

networks:
  campaign-network:
    external: true

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      campaign-network:
        ipv4_address: 10.0.5.2

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: campaign-topic:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://10.0.5.3:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      campaign-network:
        ipv4_address: 10.0.5.3

  campaign:
    image: bapadua/campaign
    build:
      context: ./campaign
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: test
    ports:
      - 8081:8081
    depends_on:
      - kafka
    networks:
      campaign-network:
        ipv4_address: 10.0.5.4

  partner:
    image: bapadua/partner
    build:
      context: ./partner
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 8082:8082
    depends_on:
      - kafka
    networks:
      campaign-network:
        ipv4_address: 10.0.5.5