server:
  port: 8081

spring:
  application:
    name: campaign
  profiles:
    active: test
  kafka:
    producer:
      bootstrap-servers:
        - 10.0.5.1:9092

---

spring:
  profiles: test
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate-ddl: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

